---
# tasks file for autorestic
- name: Override ansible_architecture
  ansible.builtin.set_fact:
    ansible_architecture: "{{ autorestic_architecture }}"
  when: autorestic_architecture is defined

- name: Import removal tasks
  ansible.builtin.import_tasks: removal.yml
  when: autorestic_state == "absent"

- name: End play when autorestic_state is absent
  ansible.builtin.meta: end_host
  when: autorestic_state == "absent"

- name: Install bzip2
  ansible.builtin.package:
    name: bzip2
    state: present
  become: true

- name: "Check restic is installed at version {{ autorestic_restic_version }}"
  ansible.builtin.command:
    cmd: restic version
  register: restic_install_status
  changed_when: not restic_install_status.stdout is search(autorestic_restic_version)
  ignore_errors: true

- name: Import restic install tasks
  ansible.builtin.import_tasks: restic.yml
  when: restic_install_status.rc != 0 or not restic_install_status.stdout is search(autorestic_restic_version)

- name: "Check autorestic is installed at version {{ autorestic_version }}"
  ansible.builtin.command:
    cmd: autorestic --version
  register: autorestic_install_status
  changed_when: not autorestic_install_status.stdout is search(autorestic_version)
  ignore_errors: true

- name: Import autorestic install tasks
  ansible.builtin.import_tasks: autorestic.yml
  when: autorestic_install_status.rc != 0 or not autorestic_install_status.stdout is search(autorestic_version)

- name: Get facts to reset ansible_architecture
  ansible.builtin.setup:
  when: autorestic_architecture is defined

- name: Create autorestic configuration file
  ansible.builtin.copy:
    content: "{{ autorestic_config | to_yaml }}"
    dest: ~/.autorestic.yml
    mode: "0600"

- name: Ensure autorestic log path exists
  ansible.builtin.file:
    path: "{{ autorestic_log_path }}"
    state: directory
    mode: "0755"

- name: Run autorestic info
  ansible.builtin.command:
    cmd: autorestic info
  changed_when: false
  when: autorestic_info

- name: Run autorestic check
  ansible.builtin.command:
    cmd: autorestic check
  register: autorestic_check_status
  changed_when: "'Everything is fine.' not in autorestic_check_status.stdout"
  when: autorestic_check

- name: Configure autorestic crontab
  when: autorestic_cron
  block:
    - name: Configure autorestic crontab PATH
      ansible.builtin.cron:
        name: PATH
        env: true
        job: /usr/local/bin:/usr/bin:/bin

    - name: Configure autorestic crontab job
      ansible.builtin.cron:
        name: Configure autorestic crontab job
        minute: "*/5"
        job: |
          {% if autorestic_cron_verbose == true %}
          OUTPUT=$({{autorestic_install_directory.path}}/autorestic cron --ci -vvvvv -c ~/.autorestic.yml 2>&1); [ "$OUTPUT" ] && echo "$OUTPUT" >> {{autorestic_log_path}}/autorestic_$(date +\%Y\%m\%d\%H\%M\%S).log
          {% else %}
          OUTPUT=$({{autorestic_install_directory.path}}/autorestic cron --ci --lean -c ~/.autorestic.yml 2>&1); [ "$OUTPUT" ] && echo "$OUTPUT" >> {{autorestic_log_path}}/autorestic_$(date +\%Y\%m\%d\%H\%M\%S).log
          {% endif %}
